config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    put :toggle_hide, on: :member
    # get :hashtags, on: :member, param: :name
  end

  get "/questions/hashtags/:name", to: "questions#hashtags"

  resource :session, only: %i[new create destroy]
  resources :users, except: %i[index], param: :nickname
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group_tag.rb
class GroupTag < ActiveRecord::Base
  # Модель связи вопросов и тэгов
  belongs_to :question
  belongs_to :tag
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: 'User', optional: true
  belongs_to :user

  # Вопрос может иметь много тэгов (запрос через таблицу связей)
  has_many :questions_tags, dependent: :destroy
  has_many :tags, through: :questions_tags

  after_commit :update_question_tags

  validates :body, presence: true, length: { maximum: 280 }

  private

  def update_question_tags
    tags.clear
    hashtags = "#{body.to_s} #{answer.to_s}".downcase.scan(Tag::REGEXP)
    tags <<
      hashtags.uniq.map do |hashtag|
        Tag.create_or_find_by(name: hashtag.delete("#"))
      end
  end
end

app/models/questions_tag.rb
# Модель связи вопросов и тэгов
class QuestionsTag < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Тэг может быть упомянут во многих вопросах (запрос через таблицу связей)
  has_many :questions_tags, dependent: :destroy
  has_many :questions, through: :questions_tags

  REGEXP = /#[[:word:]-]+/

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :delete_all

  has_secure_password

  before_save :downcase_nickname

  def to_param
    nickname
  end

  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 80, default: 'robohash')


  private

  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 40 }, format: { with: /\A[0-9a-z_]+\z/i }
  validates :header_color, format: { with: /\A#([[:xdigit:]]{3}){1,2}\z/i }

  def downcase_nickname
    nickname.downcase!
  end

  def hidden?
    hidden
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[edit update destroy]
  before_action :set_question_for_current_user, only: %i[edit update toggle_hide destroy]

  def index
    @questions = Question.order(created_at: :desc).last(10)
    @users = User.order(created_at: :desc).last(10)

    @tags = Tag.order("name").all.map{ |tag| "#" + tag.name }.join(", ")
  end

  def toggle_hide
    @question.toggle(:hidden).save

    redirect_to user_path(@question.user), notice: @question.hidden? ? 'Вопрос скрыт!' : 'Вопрос отображён!'
  end

  def hashtags
    @question = Question.new

    @tag = Tag.find_by(name: params[:name].downcase)
    @questions = @tag.questions
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(question_params)

    # Если пользователь не залогинен, то запишется nil (анонимный автор)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'Новый вопрос добавлен'
    else
      flash[:alert] = 'Допущены ошибки в вопросе'

      render :new, status: 422
    end
  end

  def edit
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    @question.assign_attributes(question_params)

    if @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос сохранён'
    else
      # debugger
      flash[:alert] = "Допущены ошибки в вопросе"

      render :edit, status: 422
    end
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Вопрос удалён!'
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def show
    @questions = @user.questions.order(:id)
    @question = Question.new(author: nil, user: @user)
  end

  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  private

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :header_color, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def render_with_hashtags(body)
    body
      .gsub(Tag::REGEXP) { |word| link_to word, "/questions/hashtags/#{word.downcase.delete("#")}" }
      .gsub(/\n/, "<br/>")
      .html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="<%= "background-color: #{current_user.header_color}" if current_user %>">
        <p class="title-sm text-bold"><%= link_to 'Ask me!', root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to display_nickname(current_user), user_path(current_user), class: 'mr-sm' %>
            <%= button_to 'Выйти', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Регистрация', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Вход', new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
  <%= form.hidden_field :user_id %>

  <% current_user.nil? ? placeholder = "Анонимный вопрос" : placeholder = "Вопрос от @#{current_user.nickname}" %>

  <p><%= form.label :body, 'Текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: "form-text-area", placeholder: placeholder %></p>

  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Ответ' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %> или <%= link_to 'Вернуться', :back %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
  <% if question.author.nil? %>
    Анонимно
  <% else %>
    Спрашивает <%= link_to display_nickname(question.author), user_path(question.author), class: 'mr-sm' %>
  <% end %>
</div>

<div class="mb-sm">
  <%= h(render_with_hashtags(question.body)) %>
</div>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <%= h(render_with_hashtags(question.answer)) %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = (question.answer.present? ? 'pencil 2x' : 'reply 2x') %>
      <% edit_title = (question.answer.present? ? 'Изменить вопрос' : 'Ответить') %>

      <%= link_to fa_icon(edit_icon), edit_question_path(question),
        title: edit_title, class: 'mr-sm' %>
      <%= button_to(fa_icon('eye-slash 2x'), toggle_hide_question_path(question), method: :put, title: 'Скрыть вопрос') unless question.hidden? %>
      <%= button_to(fa_icon('eye 2x'), toggle_hide_question_path(question), method: :put, title: 'Отобразить вопрос') if question.hidden? %>
      <%= button_to fa_icon('trash-o 2x'), question_path(question), method: :delete,
  title: 'Удалить вопрос', form: {data: {turbo_confirm: 'Точно удалить вопрос?'}} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>

  <% if @question.errors.any? %>
    <div class="mt">
      <% @question.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= render 'form', question: @question %>
</div>

app/views/questions/hashtags.html.erb
<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>  (<%= render_with_hashtags("#" + @tag.name) %>) </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container<%= " block-hide" if question.hidden? %>">
    <%= render question %>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">
    Недавно добавились
  </h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    Хэштеги: <%= render_with_hashtags(@tags) %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class="mt-sm container">
    <p class="mb text-sm text-grey">
    Вопрос <%= link_to "##{question.id}", question_path(question) %>
    для <%= link_to "@#{question.user.nickname}", user_path(question.user) %>
    </p>
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Новый вопрос</h2>

  <% if @question.errors.any? %>
    <div class="mt">
      <% @question.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <p class="mb">для <%= link_to display_nickname(@question.user), user_path(@question.user) %></p>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>
  <p class="mt-sm"><%= link_to "Все вопросы @#{@question.user.nickname}", user_path(@question.user) %></p>
</div>

<div class="container mt-sm">
  <%= render 'question', question: @question %>
</div>

app/views/users/_no_questions.html.erb
<div class="container text-center">
  <p class="title-sm text-grey">
    У этого пользователя пока никто ничего не спросил
  </p>

  <div class="mt-lg mb-lg fa-4x text-light-grey">
    <%= fa_stacked_icon 'question', base: 'circle-o' %>
  </div>

  <%= link_to "Дай, спрошу!", new_question_path(user_id: user.id),
    class: 'button button-main' %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Редактирование пользователя</h2>

  <div class="mt">
    <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
    <p class="text-sm">Чтобы добавить или поменять аватар — зарегистрируйтесь на
      <%= link_to "Gravatar", 'https://gravatar.com' %> и загрузите фото</p>
  </div>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :header_color, 'Цвет шапки профиля' %></p>
      <p><%= form.color_field :header_color, class: 'form-text-field' %></p>

      <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

      <p class="mt"><%= form.label :password, 'Пароль' %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to "вернуться", :back %></span>
      </p>
    <% end %>
  </div>

  <div class="mt-lg">
    <%= button_to "Удалить профиль", user_path(@user),
      method: :delete,
      form: {data: {turbo_confirm: "Вы точно хотите удалить свой профиль?"}},
      class: 'text-red text-sm' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Ваше имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class="mt-lg"><%= form.submit 'Зарегистрироваться', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-box">
  <h2 class="title-lg mt-lg"><%= @user.name %></h2>

  <div class="mt">
    <%= render partial: 'users/user_avatar', locals: {user: @user} %>
  </div>

  <% if current_user == @user %>
    <p class="mt mb-lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
    </p>
  <% end %>

  <p class="text-bold mt mb-lg">@<%= @user.nickname %></p>
</div>

<% if @questions.any? %>
  <div class="container">
    <%= link_to "Спроси меня", new_question_path(user_id: @user.id),
      class: 'button button-yellow' %>

    <p class="mt">
      <%= render 'questions/form', question: @question %>
    </p>
  </div>

  <div class="container mt-sm">
    <h2 class="title-lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  </div>

  <% @questions.each do |question| %>
    <div class="mt-sm container<%= " block-hide" if question.hidden? %>">
      <%= render question %>
    </div>
  <% end %>
<% else %>
  <%= render partial: 'no_questions', locals: {user: @user} %>
<% end %>